name: push-images
run-name: push images

on:
  pull_request:
    branches: [main]
    types: [closed]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push-images:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.REPO_IAM_ROLE }}
          aws-region: ${{ secrets.REPO_ECR_REGION }}
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v31
      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1073741824
          purge: true
          purge-prefixes: cache-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never
      - uses: cachix/cachix-action@v14
        with:
          name: ajenkins-public
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: docker/setup-qemu-action@v3
      - name: Run `nix build`
        run: |
          nix develop --command bash -c "nix-fast-build --no-nom --flake '.#packages'"
      - name: Login to ECR
        run: nix develop --command bash -c "aws ecr get-login-password --region ${{ secrets.REPO_ECR_REGION }}" | podman login --username AWS --password-stdin ${{ secrets.ACCOUNT_ECR_REPO }}
      - name: Create and push manifest
        run: |
          REPO="${{ secrets.ACCOUNT_ECR_REPO }}/${{ secrets.ECR_IMAGE_NAME }}"
          TAG=$(date +'%Y-%m-%d_%H-%M')
          podman manifest create "$REPO:$TAG"
          podman manifest add "$REPO:$TAG" docker-archive:result-x86_64-linux.container_aarch64 &
          podman manifest add "$REPO:$TAG" docker-archive:result-x86_64-linux.container_x86_64 &
          wait
          podman manifest push --all --rm "$REPO:$TAG" "docker://$REPO:$TAG"
          echo "Pushed: $REPO:$TAG"
